- name: setting up catalogue component
  hosts: catalogue
  become: yes
  tasks:

  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: installing
    ansible.builtin.dnf: 
      name: nodejs 
      state: present
  
  - name: creating the user 
    ansible.builtin.user:
      name: roboshop

  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading and unzipping
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /app
      remote_src: true

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copying catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon reloading
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enabling and starting catalogue 
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: true

  - name: copying mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
      
  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.sureshvadde.online < /app/schema/catalogue.js

  - name: restarting catalogue 
    ansible.builtin.service:
      name: catalogue
      state: restarted




