- name: setting up cart component
  hosts: cart
  become: yes
  tasks:

  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: installing
    ansible.builtin.dnf: 
      name: nodejs 
      state: present
  
  - name: creating the user 
    ansible.builtin.user:
      name: roboshop

  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading and unzipping
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /app

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copying cart service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon reloading
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enabling and starting cart 
    ansible.builtin.service:
      name: cart
      state: started
      enabled: true

  




