- name: setting up shipping component
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:

  - name: installing maven
    ansible.builtin.dnf:
      name: maven
      state: installed

  - name: creating the user 
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent    

  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading and unzipping
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /app
      remote_src: true

  - name: Install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copying shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemon reloading
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: install mysql client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: load catalogue data
    ansible.builtin.shell: "mysql -h mysql.sureshvadde.online -uroot -p{{mysql_password}} < /app/schema/shipping.sql" 

  - name: restarting shipping 
    ansible.builtin.service:
      name: shipping
      state: restarted 
      enabled: true    