- name: setting up rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
    - name: installing repos by vendor
      ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash ; https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: installing rabbitmq 
      ansible.builtin.dnf: 
        name: rabbitmq-server
        state: present

    - name: enabling rabbitmq
      ansible.builtin.service:
        state: started
        enabled: yes

    - name: creating user and setting permissions
      community.rabbitmq.rabbitmq_user:
        user: joe
        password: changeme
        permissions:
          - vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        state: present
